# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    routing_loader: false
    body_listener: true   
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        view_response_listener: true
        formats: { json: true, xml: false, rss: false }
    serializer:
        serialize_null: true    
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: '^/', stop: true }
    exception:
        enabled: true
        codes:
            { Symfony\Component\Routing\Exception\ResourceNotFoundException: 404 }
        messages:
            { Symfony\Component\Routing\Exception\ResourceNotFoundException: true }
