# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    view:
        view_response_listener: true
        formats: { json: true, xml: false, rss: false }
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: 'json' }
    exception:
        enabled: true
        codes:
            { Symfony\Component\Routing\Exception\ResourceNotFoundException: 404 }
        messages:
            { Symfony\Component\Routing\Exception\ResourceNotFoundException: true }
